package moe.hilaryoi.im.gui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Properties;

public class Settings { // TODO: autogenerated settingsframe // TODO: take a logger and log "does not existing... creating at ... path!!!"

	private Properties properties;

	public Settings(String fileName) throws IOException { // search home; if not there generate from default res folder

		Path homeConfigPath = Paths.get(System.getProperty("user.home"), ".IM", fileName);

		if (!Files.exists(homeConfigPath)) { // create from default if not exist

			Files.createDirectories(homeConfigPath.getParent());
			Files.createFile(homeConfigPath);

			Files.copy(this.getClass().getResourceAsStream("/" + fileName), homeConfigPath, StandardCopyOption.REPLACE_EXISTING); // why /?

		}

		properties = new Properties();
		properties.load(Files.newInputStream(homeConfigPath));

	}

	public String getString(String key) { return properties.getProperty(key); }
	public int getInteger(String key) { return Integer.parseInt(getString(key)); }
	public boolean getBoolean(String key) { return Boolean.parseBoolean(getString(key)); }

}
